spring.application.name=car-rental-chatbot

server.port=8080

ai.api.key=${OPENROUTER_API_KEY}
ai.api.url=https://openrouter.ai/api/v1/chat/completions
ai.model=openai/gpt-oss-120b:free
ai.app.name=Car Rental Chatbot